# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pallavipritibundle"
client_id = "4b3bd2ee37ab12602d2e4db266a67752"
application_url = "https://entrepreneur-encouraged-eg-portable.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_price_rules,write_discounts,read_content,write_content,write_orders,read_themes"

[auth]
redirect_urls = [
  "https://entrepreneur-encouraged-eg-portable.trycloudflare.com/auth/callback",
  "https://entrepreneur-encouraged-eg-portable.trycloudflare.com/auth/shopify/callback",
  "https://entrepreneur-encouraged-eg-portable.trycloudflare.com/api/auth/callback",
  "https://entrepreneur-encouraged-eg-portable.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "playgroundstoree.myshopify.com"
