# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d2a22c5ede7eb9ed65436e4d5b3d85fb"
name = "akashbundle"
handle = "akashbundle"
application_url = "https://dir-tones-gallery-recommended.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "robins-store1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_content,read_customers,read_orders,read_themes,unauthenticated_read_checkouts,unauthenticated_write_checkouts,write_checkouts,write_content,write_discounts,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://dir-tones-gallery-recommended.trycloudflare.com/auth/callback",
  "https://dir-tones-gallery-recommended.trycloudflare.com/auth/shopify/callback",
  "https://dir-tones-gallery-recommended.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
